Run unit tests for the api submodule in addition to the integration tests

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -4,6 +4,36 @@ on:
   pull_request:
 
 jobs:
+  apiunits:
+    runs-on: ubuntu-latest
+    permissions:
+      contents: write
+      pull-requests: write
+      checks: write
+    strategy:
+      matrix:
+        python-version: ["3.11"] # , "3.12"]
+    steps:
+      - uses: actions/checkout@v3
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v4
+        with:
+          python-version: ${{ matrix.python-version }}
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install poetry
+          cd api && poetry install
+      - name: Test with pytest
+        run: |
+          cd api && poetry run py.test -v --junitxml=pytest.xml
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/pytest*.xml'
+          detailed_summary: true
+          check_name: 'JUnit report (api units)'
   rmlocal:
     runs-on: ubuntu-latest
     permissions:
